import type { Layouts } from "react-grid-layout";

import type {
  CurrencyCode,
  DashboardSnapshot,
  MarketInstrument,
  Position,
  PnlPoint,
  TradingAccount,
  TradingSession,
  TradingStats,
  Transaction,
  WidgetId,
  SocialStrategy, // Added import
} from "@/types/dashboard";

export const MOCK_SOCIAL_STRATEGIES: SocialStrategy[] = [
  {
    id: "s1",
    name: "elite market concepts",
    description: "low risk , high reward",
    avatar: "E",
    riskLevel: "Medium",
    totalProfit: -22.95,
    winRate: 47.83,
    maxDrawdown: 0.00,
    followers: 7,
    trades: 23,
    profitFactor: 2.4,
    sharpeRatio: 1.8,
    avgTradePnl: 125.50,
    bestTrade: 500.00,
    worstTrade: -150.00,
    masterEquity: 25000.00,
    minBalance: 500,
    recoveryFactor: 1.5,
    expectedPayoff: 12.50,
    monthlyReturns: [
      { year: 2026, jan: 5.2, feb: -2.1 },
      { year: 2025, jan: 1.2, feb: 3.4, mar: -1.0, apr: 4.5, may: 2.1, jun: 0.5, jul: 3.2, aug: 1.1, sep: -0.5, oct: 2.8, nov: 1.9, dec: 0.8 }
    ],
    longTradesStats: { total: 15, won: 10, avgProfit: 150, avgLoss: -50 },
    shortTradesStats: { total: 8, won: 5, avgProfit: 120, avgLoss: -40 },
    fee: 0,
    performanceFee: 20,
    joinedAt: "2025-11-15T00:00:00Z",
    tags: ["Scalping", "Day Trading"],
    chartData: [
      { date: "Jan", value: 100 },
      { date: "Feb", value: 95 },
      { date: "Mar", value: 90 },
      { date: "Apr", value: 85 },
      { date: "May", value: 80 },
      { date: "Jun", value: 82 },
      { date: "Jul", value: 77.05 }
    ]
  },
  {
    id: "s2",
    name: "Gold trading",
    description: "Trading Gold : a high liquid metal !",
    avatar: "G",
    riskLevel: "Medium",
    totalProfit: 1205.04,
    winRate: 52.14,
    maxDrawdown: 0.00,
    followers: 3,
    trades: 2238,
    profitFactor: 1.8,
    sharpeRatio: 1.2,
    avgTradePnl: 80.00,
    bestTrade: 300.00,
    worstTrade: -100.00,
    masterEquity: 15000.00,
    minBalance: 1000,
    recoveryFactor: 0.9,
    expectedPayoff: -2.24,
    monthlyReturns: [
      { year: 2026, feb: -23 },
      { year: 2025, jul: -29 }
    ],
    longTradesStats: { total: 8, won: 6, avgProfit: 2.05, avgLoss: -3.52 },
    shortTradesStats: { total: 15, won: 5, avgProfit: 0.70, avgLoss: -3.35 },
    fee: 10,
    performanceFee: 15,
    joinedAt: "2025-01-10T00:00:00Z",
    tags: ["Gold", "Swing"],
    chartData: [
      { date: "Jan", value: 100 },
      { date: "Feb", value: 150 },
      { date: "Mar", value: 300 },
      { date: "Apr", value: 450 },
      { date: "May", value: 600 },
      { date: "Jun", value: 850 },
      { date: "Jul", value: 1305.04 }
    ]
  },
  {
    id: "s3",
    name: "Gold Precision Scalper",
    description: "A disciplined gold (XAUUSD) trading strategy based on technical analysis and...",
    avatar: "G",
    riskLevel: "Medium",
    totalProfit: 88.93,
    winRate: 62.32,
    maxDrawdown: 0.00,
    followers: 2,
    trades: 138,
    profitFactor: 3.1,
    sharpeRatio: 2.5,
    avgTradePnl: 45.00,
    bestTrade: 150.00,
    worstTrade: -20.00,
    masterEquity: 5000.00,
    minBalance: 100,
    recoveryFactor: 2.1,
    expectedPayoff: 8.40,
    monthlyReturns: [
      { year: 2026, jan: 2.5, feb: 1.8 },
      { year: 2025, dec: 4.2 }
    ],
    longTradesStats: { total: 80, won: 50, avgProfit: 50, avgLoss: -20 },
    shortTradesStats: { total: 58, won: 30, avgProfit: 45, avgLoss: -15 },
    fee: 5,
    performanceFee: 10,
    joinedAt: "2026-01-05T00:00:00Z",
    tags: ["Gold", "Scalping"],
    chartData: [
      { date: "Jan", value: 100 },
      { date: "Feb", value: 90 },
      { date: "Mar", value: 120 },
      { date: "Apr", value: 110 },
      { date: "May", value: 140 },
      { date: "Jun", value: 160 },
      { date: "Jul", value: 188.93 }
    ]
  },
  {
    id: "s4",
    name: "Steady gorwth",
    description: "Buckle up the seats belt",
    avatar: "S",
    riskLevel: "Medium",
    totalProfit: 0.80,
    winRate: 50.00,
    maxDrawdown: 0.00,
    followers: 1,
    trades: 4,
    profitFactor: 5.0,
    sharpeRatio: 3.0,
    avgTradePnl: 200.00,
    bestTrade: 400.00,
    worstTrade: 0.00,
    masterEquity: 10000.00,
    minBalance: 2000,
    recoveryFactor: 3.5,
    expectedPayoff: 50.00,
    monthlyReturns: [
      { year: 2026, jan: 1.0, feb: 1.2 }
    ],
    longTradesStats: { total: 2, won: 2, avgProfit: 200, avgLoss: 0 },
    shortTradesStats: { total: 2, won: 1, avgProfit: 150, avgLoss: -50 },
    fee: 0,
    performanceFee: 20,
    joinedAt: "2026-02-01T00:00:00Z",
    tags: ["Conservative"],
    chartData: [
      { date: "Jan", value: 100 },
      { date: "Feb", value: 100.1 },
      { date: "Mar", value: 100.2 },
      { date: "Apr", value: 100.4 },
      { date: "May", value: 100.6 },
      { date: "Jun", value: 100.7 },
      { date: "Jul", value: 100.8 }
    ]
  },
  {
    id: "s5",
    name: "IFX",
    description: "One or two trades a day.",
    avatar: "I",
    riskLevel: "Medium",
    totalProfit: 11.53,
    winRate: 72.73,
    maxDrawdown: 0.00,
    followers: 1,
    trades: 11,
    profitFactor: 1.5,
    sharpeRatio: 0.8,
    avgTradePnl: 50.00,
    bestTrade: 120.00,
    worstTrade: -80.00,
    masterEquity: 2000.00,
    minBalance: 100,
    recoveryFactor: 0.5,
    expectedPayoff: 5.00,
    monthlyReturns: [
      { year: 2026, jan: -1.5 },
      { year: 2025, dec: 2.0 }
    ],
    longTradesStats: { total: 5, won: 2, avgProfit: 60, avgLoss: -40 },
    shortTradesStats: { total: 6, won: 3, avgProfit: 55, avgLoss: -50 },
    fee: 0,
    performanceFee: 20,
    joinedAt: "2025-12-20T00:00:00Z",
    tags: ["Day Trading"],
    chartData: [
      { date: "Jan", value: 100 },
      { date: "Feb", value: 102 },
      { date: "Mar", value: 105 },
      { date: "Apr", value: 108 },
      { date: "May", value: 107 },
      { date: "Jun", value: 109 },
      { date: "Jul", value: 111.53 }
    ]
  },
  {
    id: "s6",
    name: "M7P",
    description: "Aim to low risk, steady growth",
    avatar: "M",
    riskLevel: "Medium",
    totalProfit: 7.15,
    winRate: 93.33,
    maxDrawdown: 0.00,
    followers: 0,
    trades: 15,
    profitFactor: 9.9,
    sharpeRatio: 4.5,
    avgTradePnl: 30.00,
    bestTrade: 50.00,
    worstTrade: -5.00,
    masterEquity: 3000.00,
    minBalance: 50,
    recoveryFactor: 5.0,
    expectedPayoff: 15.00,
    monthlyReturns: [
      { year: 2026, jan: 3.5, feb: 4.0 }
    ],
    longTradesStats: { total: 10, won: 9, avgProfit: 40, avgLoss: -10 },
    shortTradesStats: { total: 5, won: 5, avgProfit: 35, avgLoss: 0 },
    fee: 0,
    performanceFee: 30,
    joinedAt: "2026-02-10T00:00:00Z",
    tags: ["Low Risk"],
    chartData: [
      { date: "Jan", value: 100 },
      { date: "Feb", value: 101 },
      { date: "Mar", value: 102 },
      { date: "Apr", value: 103 },
      { date: "May", value: 105 },
      { date: "Jun", value: 106 },
      { date: "Jul", value: 107.15 }
    ]
  },
  {
    id: "s7",
    name: "Pure Price Action",
    description: "Trading on higher timeframe",
    avatar: "P",
    riskLevel: "Medium",
    totalProfit: 0.40,
    winRate: 62.50,
    maxDrawdown: 0.00,
    followers: 0,
    trades: 8,
    profitFactor: 1.2,
    sharpeRatio: 0.5,
    avgTradePnl: 10.00,
    bestTrade: 80.00,
    worstTrade: -60.00,
    masterEquity: 1200.00,
    minBalance: 100,
    recoveryFactor: 1.1,
    expectedPayoff: 2.50,
    monthlyReturns: [
      { year: 2025, nov: 1.5, dec: -0.5 }
    ],
    longTradesStats: { total: 4, won: 2, avgProfit: 30, avgLoss: -20 },
    shortTradesStats: { total: 4, won: 2, avgProfit: 25, avgLoss: -15 },
    fee: 0,
    performanceFee: 25,
    joinedAt: "2025-10-01T00:00:00Z",
    tags: ["Price Action", "Swing"],
    chartData: [
      { date: "Jan", value: 100 },
      { date: "Feb", value: 100.1 },
      { date: "Mar", value: 100.05 },
      { date: "Apr", value: 100.2 },
      { date: "May", value: 100.3 },
      { date: "Jun", value: 100.35 },
      { date: "Jul", value: 100.4 }
    ]
  },
  {
    id: "s8",
    name: "Forexwickeyes",
    description: "Price action Trader",
    avatar: "F",
    riskLevel: "Low",
    totalProfit: -37.15,
    winRate: 53.57,
    maxDrawdown: 0.00,
    followers: 0,
    trades: 28,
    profitFactor: 0.8,
    sharpeRatio: -0.2,
    avgTradePnl: -15.00,
    bestTrade: 40.00,
    worstTrade: -90.00,
    masterEquity: 800.00,
    minBalance: 100,
    recoveryFactor: -0.1,
    expectedPayoff: -5.00,
    monthlyReturns: [
      { year: 2025, sep: -2.0, oct: -1.5 }
    ],
    longTradesStats: { total: 14, won: 5, avgProfit: 20, avgLoss: -30 },
    shortTradesStats: { total: 14, won: 4, avgProfit: 15, avgLoss: -25 },
    fee: 0,
    performanceFee: 30,
    joinedAt: "2025-08-15T00:00:00Z",
    tags: ["Price Action"],
    chartData: [
      { date: "Jan", value: 100 },
      { date: "Feb", value: 90 },
      { date: "Mar", value: 85 },
      { date: "Apr", value: 80 },
      { date: "May", value: 75 },
      { date: "Jun", value: 70 },
      { date: "Jul", value: 62.85 }
    ]
  }
];

export const DASHBOARD_WIDGET_ORDER: WidgetId[] = [
  "account-overview",
  "market-overview",
  "deposit-withdrawal",
  "trading-sessions",
  "active-positions",
  "recent-trades",
  "entertainment",
];

// Default MT5 server IP used by the local/standalone fallback accounts.
const MOCK_SERVER_IP = "89.21.67.29";

const buildMockStats = (overrides: Partial<TradingStats> = {}): TradingStats => ({
  totalTrades: 0,
  winRate: 0,
  profitFactor: 0,
  totalVolume: 0,
  winningTrades: 0,
  losingTrades: 0,
  averageWin: 0,
  averageLoss: 0,
  largestWin: 0,
  largestLoss: 0,
  consecutiveWins: 0,
  consecutiveLosses: 0,
  totalCommission: 0,
  totalSwap: 0,
  ...overrides,
});

// Hardcoded sample accounts so the standalone terminal (mock data source) renders
// a populated account switcher, account-overview and statistics widgets with no backend.
export const MOCK_TRADING_ACCOUNTS: TradingAccount[] = [
  {
    id: "acc-live-900847",
    accountNumber: "900847",
    name: "FlexyMarkets Live",
    platform: "mt5",
    type: "Live",
    leverage: 500,
    serverIp: MOCK_SERVER_IP,
    currency: "USD",
    balance: 15280.45,
    equity: 15412.10,
    freeMargin: 14180.32,
    margin: 1231.78,
    status: "Active",
    createdAt: "2026-03-12T09:24:00.000Z",
    credentials: {
      login: "900847",
      server: "FlexyMarkets-Live",
      tradingPassword: "Trade!2026Xk",
      investorPassword: "View!2026Yz",
      generatedAt: "2026-03-12T09:24:00.000Z",
      source: "broker",
    },
    transactions: [],
    stats: buildMockStats({
      totalTrades: 148,
      winRate: 61.5,
      profitFactor: 1.84,
      totalVolume: 312.4,
      winningTrades: 91,
      losingTrades: 57,
      averageWin: 142.8,
      averageLoss: -86.3,
      largestWin: 980.5,
      largestLoss: -512.2,
      consecutiveWins: 7,
      consecutiveLosses: 3,
      totalCommission: -184.2,
      totalSwap: -42.7,
    }),
  },
  {
    id: "acc-demo-5012334",
    accountNumber: "5012334",
    name: "MetaTrader 5 Demo",
    platform: "mt5",
    type: "Demo",
    leverage: 100,
    serverIp: MOCK_SERVER_IP,
    currency: "USD",
    balance: 10000,
    equity: 10000,
    freeMargin: 10000,
    margin: 0,
    status: "Active",
    createdAt: "2026-05-28T14:10:00.000Z",
    credentials: {
      login: "5012334",
      server: "FlexyMarkets-Demo",
      tradingPassword: "Trade!2026Aa",
      investorPassword: "View!2026Bb",
      generatedAt: "2026-05-28T14:10:00.000Z",
      source: "broker",
    },
    transactions: [],
    stats: buildMockStats({
      totalTrades: 32,
      winRate: 53.1,
      profitFactor: 1.32,
      totalVolume: 58.2,
      winningTrades: 17,
      losingTrades: 15,
      averageWin: 64.5,
      averageLoss: -48.9,
      largestWin: 210.0,
      largestLoss: -132.4,
      consecutiveWins: 4,
      consecutiveLosses: 2,
    }),
  },
];

export const WIDGET_META: Record<WidgetId, { title: string; description: string; category: "account" | "market" | "trading" | "tools"; size: "small" | "medium" | "large" }> = {
  "account-overview": {
    title: "Account Overview",
    description: "Balance, equity, margin level, and P&L summary",
    category: "account",
    size: "large"
  },
  "trading-statistics": {
    title: "Trading Statistics",
    description: "Performance metrics and trading insights",
    category: "trading",
    size: "medium"
  },
  "recent-trades": {
    title: "Recent Trades",
    description: "Trade history with performance analysis",
    category: "trading",
    size: "large"
  },
  "entertainment": {
    title: "Entertainment",
    description: "Fun games for traders - roulette, card color, crash",
    category: "tools",
    size: "medium"
  },
  "market-overview": {
    title: "Market Overview",
    description: "Currency pair prices and market sentiment",
    category: "market",
    size: "large"
  },
  "deposit-withdrawal": {
    title: "Deposit & Withdrawal",
    description: "Quick funding options and transaction history",
    category: "account",
    size: "medium"
  },
  "trading-sessions": {
    title: "Trading Sessions",
    description: "Global trading sessions and optimal trading times",
    category: "market",
    size: "medium"
  },
  "active-positions": {
    title: "Active Positions",
    description: "Current open positions with real-time P&L",
    category: "trading",
    size: "medium"
  },
};

export const DEFAULT_WIDGET_LAYOUTS: Layouts = {
  lg: [
    { i: "market-overview", x: 0, y: 0, w: 6, h: 14, minW: 4, minH: 8 },
    { i: "deposit-withdrawal", x: 6, y: 0, w: 6, h: 14, minW: 4, minH: 8 },
    { i: "trading-sessions", x: 0, y: 14, w: 6, h: 14, minW: 4, minH: 8 },
    { i: "active-positions", x: 6, y: 14, w: 6, h: 14, minW: 4, minH: 8 },
    { i: "account-overview", x: 0, y: 28, w: 6, h: 14, minW: 4, minH: 8 },
    { i: "trading-statistics", x: 6, y: 28, w: 6, h: 14, minW: 4, minH: 8 },
    { i: "entertainment", x: 0, y: 42, w: 6, h: 28, minW: 4, minH: 16 },
    { i: "recent-trades", x: 6, y: 42, w: 6, h: 14, minW: 4, minH: 8 },
  ],
  md: [
    { i: "market-overview", x: 0, y: 0, w: 5, h: 14, minW: 3, minH: 8 },
    { i: "deposit-withdrawal", x: 5, y: 0, w: 5, h: 14, minW: 3, minH: 8 },
    { i: "trading-sessions", x: 0, y: 14, w: 5, h: 14, minW: 3, minH: 8 },
    { i: "active-positions", x: 5, y: 14, w: 5, h: 14, minW: 3, minH: 8 },
    { i: "account-overview", x: 0, y: 28, w: 5, h: 14, minW: 3, minH: 8 },
    { i: "trading-statistics", x: 5, y: 28, w: 5, h: 14, minW: 3, minH: 8 },
    { i: "entertainment", x: 0, y: 42, w: 5, h: 28, minW: 3, minH: 16 },
    { i: "recent-trades", x: 5, y: 42, w: 5, h: 14, minW: 3, minH: 8 },
  ],
  sm: [
    { i: "market-overview", x: 0, y: 0, w: 6, h: 14, minW: 2, minH: 8 },
    { i: "deposit-withdrawal", x: 0, y: 14, w: 6, h: 14, minW: 2, minH: 8 },
    { i: "trading-sessions", x: 0, y: 28, w: 6, h: 14, minW: 2, minH: 8 },
    { i: "active-positions", x: 0, y: 42, w: 6, h: 14, minW: 2, minH: 8 },
    { i: "account-overview", x: 0, y: 56, w: 6, h: 14, minW: 2, minH: 8 },
    { i: "trading-statistics", x: 0, y: 70, w: 6, h: 14, minW: 2, minH: 8 },
    { i: "entertainment", x: 0, y: 84, w: 6, h: 28, minW: 2, minH: 16 },
    { i: "recent-trades", x: 0, y: 98, w: 6, h: 14, minW: 2, minH: 8 },
  ],
};

export const MARKET_OVERVIEW_DATA: MarketInstrument[] = [
  {
    id: "audusd",
    name: "Aussie / USD",
    label: "AUD / USD",
    sentiment: "BUY",
    short: -28,
    medium: 18,
    long: 45,
    trend: "Neutral",
    score: 25,
  },
  {
    id: "btc",
    name: "Bitcoin / USD",
    label: "BTC / USD",
    sentiment: "SELL",
    short: 12,
    medium: -15,
    long: -25,
    trend: "Neutral",
    score: -10,
  },
  {
    id: "eurjpy",
    name: "Euro / Japanese Yen",
    label: "EUR / JPY",
    sentiment: "BUY",
    short: 5,
    medium: 15,
    long: 22,
    trend: "Neutral",
    score: 15,
  },
  {
    id: "eurusd",
    name: "Euro / US Dollar",
    label: "EUR / USD",
    sentiment: "BUY",
    short: -27,
    medium: 27,
    long: 58,
    trend: "Neutral",
    score: 30,
  },
  {
    id: "gbpjpy",
    name: "Pound / Yen",
    label: "GBP / JPY",
    sentiment: "SELL",
    short: -23,
    medium: -48,
    long: 15,
    trend: "Neutral",
    score: -2,
  },
  {
    id: "gbpusd",
    name: "Pound / US Dollar",
    label: "GBP / USD",
    sentiment: "BUY",
    short: 8,
    medium: 12,
    long: 18,
    trend: "Neutral",
    score: 10,
  },
  {
    id: "nas100",
    name: "Nasdaq 100",
    label: "NAS 100",
    sentiment: "BUY",
    short: 15,
    medium: 25,
    long: 35,
    trend: "Neutral",
    score: 42,
  },
  {
    id: "nzdusd",
    name: "NZ Dollar / US Dollar",
    label: "NZD / USD",
    sentiment: "SELL",
    short: -12,
    medium: -8,
    long: 5,
    trend: "Neutral",
    score: -5,
  },
  {
    id: "us30",
    name: "Dow Jones 30",
    label: "US 30",
    sentiment: "BUY",
    short: 10,
    medium: 18,
    long: 28,
    trend: "Neutral",
    score: 32,
  },
  {
    id: "usdcad",
    name: "US Dollar / Can Dollar",
    label: "USD / CAD",
    sentiment: "SELL",
    short: 5,
    medium: -5,
    long: -12,
    trend: "Neutral",
    score: -8,
  },
  {
    id: "usdchf",
    name: "US Dollar / Swiss Franc",
    label: "USD / CHF",
    sentiment: "BUY",
    short: -5,
    medium: 5,
    long: 12,
    trend: "Neutral",
    score: 8,
  },
  {
    id: "usdjpy",
    name: "US Dollar / Japanese Yen",
    label: "USD / JPY",
    sentiment: "BUY",
    short: 2,
    medium: 8,
    long: 15,
    trend: "Neutral",
    score: 12,
  },
  {
    id: "xauusd",
    name: "Gold / USD",
    label: "XAU / USD",
    sentiment: "BUY",
    short: -15,
    medium: 32,
    long: 42,
    trend: "Neutral",
    score: 35,
  },
];

export const TRADING_SESSIONS: TradingSession[] = [
  {
    id: "new-york",
    city: "New York",
    utcOpenHour: 13,
    utcCloseHour: 22,
    timezone: "America/New_York",
    marker: [-74.006, 40.7128],
  },
  {
    id: "london",
    city: "London",
    utcOpenHour: 8,
    utcCloseHour: 17,
    timezone: "Europe/London",
    marker: [-0.1276, 51.5074],
  },
  {
    id: "tokyo",
    city: "Tokyo",
    utcOpenHour: 0,
    utcCloseHour: 9,
    timezone: "Asia/Tokyo",
    marker: [139.6917, 35.6895],
  },
  {
    id: "sydney",
    city: "Sydney",
    utcOpenHour: 22,
    utcCloseHour: 7,
    timezone: "Australia/Sydney",
    marker: [151.2093, -33.8688],
  },
];

export const INITIAL_WALLETS: Record<CurrencyCode, number> = {
  USD: 12500,
  EUR: 3200,
};

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: "txn-1",
    type: "Deposit",
    amount: 10000,
    currency: "USD",
    method: "crypto",
    status: "Completed",
    createdAt: "2026-03-12T09:20:00.000Z",
  },
  {
    id: "txn-2",
    type: "Transfer to MT5",
    amount: 5000,
    currency: "USD",
    method: "card",
    status: "Completed",
    createdAt: "2026-03-12T09:25:00.000Z",
    targetAccount: "900847",
  },
  {
    id: "txn-3",
    type: "Deposit",
    amount: 3200,
    currency: "EUR",
    method: "card",
    status: "Completed",
    createdAt: "2026-04-02T11:02:00.000Z",
  },
  {
    id: "txn-4",
    type: "Withdrawal",
    amount: 1500,
    currency: "USD",
    method: "crypto",
    status: "Processing",
    createdAt: "2026-06-05T16:45:00.000Z",
  },
  {
    id: "txn-5",
    type: "Transfer from MT5",
    amount: 750,
    currency: "USD",
    method: "card",
    status: "Completed",
    createdAt: "2026-06-08T10:15:00.000Z",
    targetAccount: "900847",
  },
];

export const INITIAL_POSITIONS: Position[] = [
  { id: "pos-1", symbol: "EURUSD", side: "Buy", volume: 0.5, pnl: 84.2, accountLogin: "900847" },
  { id: "pos-2", symbol: "XAUUSD", side: "Buy", volume: 0.1, pnl: 142.75, accountLogin: "900847" },
  { id: "pos-3", symbol: "GBPJPY", side: "Sell", volume: 0.25, pnl: -38.4, accountLogin: "900847" },
  { id: "pos-4", symbol: "BTCUSD", side: "Buy", volume: 0.05, pnl: 268.1, accountLogin: "900847" },
  { id: "pos-5", symbol: "NAS100", side: "Sell", volume: 1.0, pnl: -52.9, accountLogin: "5012334" },
];

export const PNL_SPARKLINE: PnlPoint[] = [
  { t: "09:00", value: 0.2 },
  { t: "09:30", value: 0.38 },
  { t: "10:00", value: 0.05 },
  { t: "10:30", value: -0.12 },
  { t: "11:00", value: 0.18 },
  { t: "11:30", value: 0.34 },
  { t: "12:00", value: 0.11 },
];

export const MOCK_DASHBOARD_SNAPSHOT: DashboardSnapshot = {
  marketInstruments: MARKET_OVERVIEW_DATA,
  tradingSessions: TRADING_SESSIONS,
  wallets: INITIAL_WALLETS,
  positions: INITIAL_POSITIONS,
  transactions: INITIAL_TRANSACTIONS,
  pnlSeries: PNL_SPARKLINE,
  tradingAccounts: MOCK_TRADING_ACCOUNTS,
};
