// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/terminal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terminal">> = Specific
  const handler = {} as typeof import("../../app/terminal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/login">> = Specific
  const handler = {} as typeof import("../../app/api/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/logout">> = Specific
  const handler = {} as typeof import("../../app/api/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/me/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/me">> = Specific
  const handler = {} as typeof import("../../app/api/auth/me/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/register/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/register">> = Specific
  const handler = {} as typeof import("../../app/api/auth/register/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/dashboard/snapshot/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/snapshot">> = Specific
  const handler = {} as typeof import("../../app/api/dashboard/snapshot/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/market-news/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/market-news">> = Specific
  const handler = {} as typeof import("../../app/api/market-news/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/payments/[...path]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payments/[...path]">> = Specific
  const handler = {} as typeof import("../../app/api/payments/[...path]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/private/accounts/[accountId]/credentials/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/private/accounts/[accountId]/credentials">> = Specific
  const handler = {} as typeof import("../../app/api/private/accounts/[accountId]/credentials/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/private/accounts/[accountId]/credentials/verify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/private/accounts/[accountId]/credentials/verify">> = Specific
  const handler = {} as typeof import("../../app/api/private/accounts/[accountId]/credentials/verify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/private/accounts/[accountId]/mode/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/private/accounts/[accountId]/mode">> = Specific
  const handler = {} as typeof import("../../app/api/private/accounts/[accountId]/mode/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/private/accounts/[accountId]/ohlc-gap-fill/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/private/accounts/[accountId]/ohlc-gap-fill">> = Specific
  const handler = {} as typeof import("../../app/api/private/accounts/[accountId]/ohlc-gap-fill/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/private/accounts/[accountId]/password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/private/accounts/[accountId]/password">> = Specific
  const handler = {} as typeof import("../../app/api/private/accounts/[accountId]/password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/private/accounts/[accountId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/private/accounts/[accountId]">> = Specific
  const handler = {} as typeof import("../../app/api/private/accounts/[accountId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/private/accounts/[accountId]/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/private/accounts/[accountId]/status">> = Specific
  const handler = {} as typeof import("../../app/api/private/accounts/[accountId]/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/private/accounts/[accountId]/stored-credentials/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/private/accounts/[accountId]/stored-credentials">> = Specific
  const handler = {} as typeof import("../../app/api/private/accounts/[accountId]/stored-credentials/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/private/accounts/[accountId]/sync-balance/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/private/accounts/[accountId]/sync-balance">> = Specific
  const handler = {} as typeof import("../../app/api/private/accounts/[accountId]/sync-balance/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/private/accounts/[accountId]/terminal-ohlc-repair/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/private/accounts/[accountId]/terminal-ohlc-repair">> = Specific
  const handler = {} as typeof import("../../app/api/private/accounts/[accountId]/terminal-ohlc-repair/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/private/accounts/[accountId]/terminal-session/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/private/accounts/[accountId]/terminal-session">> = Specific
  const handler = {} as typeof import("../../app/api/private/accounts/[accountId]/terminal-session/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/private/accounts/[accountId]/terminal-state/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/private/accounts/[accountId]/terminal-state">> = Specific
  const handler = {} as typeof import("../../app/api/private/accounts/[accountId]/terminal-state/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/private/accounts/groups/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/private/accounts/groups">> = Specific
  const handler = {} as typeof import("../../app/api/private/accounts/groups/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/private/accounts/reset-all/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/private/accounts/reset-all">> = Specific
  const handler = {} as typeof import("../../app/api/private/accounts/reset-all/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/private/accounts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/private/accounts">> = Specific
  const handler = {} as typeof import("../../app/api/private/accounts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/private/accounts/sync-all-balances/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/private/accounts/sync-all-balances">> = Specific
  const handler = {} as typeof import("../../app/api/private/accounts/sync-all-balances/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/private/admin/groups/[groupName]/symbols/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/private/admin/groups/[groupName]/symbols">> = Specific
  const handler = {} as typeof import("../../app/api/private/admin/groups/[groupName]/symbols/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/private/copy-trading/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/private/copy-trading">> = Specific
  const handler = {} as typeof import("../../app/api/private/copy-trading/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/private/dashboard/positions/sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/private/dashboard/positions/sync">> = Specific
  const handler = {} as typeof import("../../app/api/private/dashboard/positions/sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/private/dashboard/snapshot/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/private/dashboard/snapshot">> = Specific
  const handler = {} as typeof import("../../app/api/private/dashboard/snapshot/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/private/journal/equity-curve/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/private/journal/equity-curve">> = Specific
  const handler = {} as typeof import("../../app/api/private/journal/equity-curve/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/private/journal/monte-carlo/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/private/journal/monte-carlo">> = Specific
  const handler = {} as typeof import("../../app/api/private/journal/monte-carlo/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/private/journal/notes/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/private/journal/notes/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/private/journal/notes/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/private/journal/notes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/private/journal/notes">> = Specific
  const handler = {} as typeof import("../../app/api/private/journal/notes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/private/journal/patterns/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/private/journal/patterns">> = Specific
  const handler = {} as typeof import("../../app/api/private/journal/patterns/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/private/journal/projections/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/private/journal/projections">> = Specific
  const handler = {} as typeof import("../../app/api/private/journal/projections/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/private/journal/reports/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/private/journal/reports">> = Specific
  const handler = {} as typeof import("../../app/api/private/journal/reports/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/private/journal/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/private/journal/stats">> = Specific
  const handler = {} as typeof import("../../app/api/private/journal/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/private/mm/accounts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/private/mm/accounts">> = Specific
  const handler = {} as typeof import("../../app/api/private/mm/accounts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/private/mm/transactions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/private/mm/transactions">> = Specific
  const handler = {} as typeof import("../../app/api/private/mm/transactions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/private/mm/transfers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/private/mm/transfers">> = Specific
  const handler = {} as typeof import("../../app/api/private/mm/transfers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/private/notifications/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/private/notifications">> = Specific
  const handler = {} as typeof import("../../app/api/private/notifications/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/private/partner/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/private/partner">> = Specific
  const handler = {} as typeof import("../../app/api/private/partner/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/private/profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/private/profile">> = Specific
  const handler = {} as typeof import("../../app/api/private/profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/private/referrals/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/private/referrals">> = Specific
  const handler = {} as typeof import("../../app/api/private/referrals/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/private/rewards/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/private/rewards">> = Specific
  const handler = {} as typeof import("../../app/api/private/rewards/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/private/settings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/private/settings">> = Specific
  const handler = {} as typeof import("../../app/api/private/settings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/private/settings/security/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/private/settings/security">> = Specific
  const handler = {} as typeof import("../../app/api/private/settings/security/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/private/settings/trading/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/private/settings/trading">> = Specific
  const handler = {} as typeof import("../../app/api/private/settings/trading/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/private/social/strategies/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/private/social/strategies">> = Specific
  const handler = {} as typeof import("../../app/api/private/social/strategies/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/private/support/tickets/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/private/support/tickets/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/private/support/tickets/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/private/support/tickets/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/private/support/tickets">> = Specific
  const handler = {} as typeof import("../../app/api/private/support/tickets/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/private/trading/history/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/private/trading/history">> = Specific
  const handler = {} as typeof import("../../app/api/private/trading/history/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/private/trading/performance/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/private/trading/performance">> = Specific
  const handler = {} as typeof import("../../app/api/private/trading/performance/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/private/verification/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/private/verification">> = Specific
  const handler = {} as typeof import("../../app/api/private/verification/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/private/wallet/funds/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/private/wallet/funds">> = Specific
  const handler = {} as typeof import("../../app/api/private/wallet/funds/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/private/wallet/transactions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/private/wallet/transactions">> = Specific
  const handler = {} as typeof import("../../app/api/private/wallet/transactions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/private/wallet/transfer/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/private/wallet/transfer">> = Specific
  const handler = {} as typeof import("../../app/api/private/wallet/transfer/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/terminal/[...path]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/terminal/[...path]">> = Specific
  const handler = {} as typeof import("../../app/api/terminal/[...path]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/test-db/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/test-db">> = Specific
  const handler = {} as typeof import("../../app/api/test-db/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/trading/account/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/trading/account">> = Specific
  const handler = {} as typeof import("../../app/api/trading/account/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/trading/auth/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/trading/auth">> = Specific
  const handler = {} as typeof import("../../app/api/trading/auth/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/trading/history/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/trading/history">> = Specific
  const handler = {} as typeof import("../../app/api/trading/history/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/trading/ohlc-history/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/trading/ohlc-history">> = Specific
  const handler = {} as typeof import("../../app/api/trading/ohlc-history/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/trading/orders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/trading/orders">> = Specific
  const handler = {} as typeof import("../../app/api/trading/orders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/trading/positions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/trading/positions">> = Specific
  const handler = {} as typeof import("../../app/api/trading/positions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/trading/symbols/group/active/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/trading/symbols/group/active">> = Specific
  const handler = {} as typeof import("../../app/api/trading/symbols/group/active/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/trading/symbols/market-status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/trading/symbols/market-status">> = Specific
  const handler = {} as typeof import("../../app/api/trading/symbols/market-status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/trading/symbols/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/trading/symbols">> = Specific
  const handler = {} as typeof import("../../app/api/trading/symbols/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/terminal/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/terminal">> = Specific
  const handler = {} as typeof import("../../app/terminal/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
